### ISSUE TITLE
Author pop-up issue in the article-detail page

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#45]
It would be desirable for the author pop-up to disappear when anyone click any other part of the page. Currently, one have to click the same author again for it to disappear.

**Comment by Vitaliy-1** [comment]
Hi @anupent 
Hmm, actually I was thinking about Bootstrap way. Can you look at `Dismissable popover` here and tell if it is what you are looking: 
https://getbootstrap.com/docs/4.0/components/popovers/#dismiss-on-next-click

**Comment by anupent** [comment]
What do you think of tooltip instead of popover. Just mouseover will bring up the tooltip. No need of clicking. When mouse is moved away, it closes automatically.
You can see here: https://jlmc.edu.np/index.php/JLMC/article/view/183

**Comment by anupent** [comment]
If you prefer popover, the above like is what I was looking for. Great.

**Comment by Vitaliy-1** [comment]
The idea was to make available a copy-pasting of authors affiliations from the popover by the user. Dismissible popover or tooltip will make this impossible. Although we have authors information under the details tab, so it really doesn't matter. 
If to choose between dismissible popover and tooltip, I'd prefer the latter, because it is more native to a user.

**Comment by anupent** [comment]
Should I commit for tooltip and create a pull request?

**Comment by Vitaliy-1** [comment]
If you do, I would be appreciative.

**Comment by anupent** [comment]
Popover replaced with tooltip.
https://github.com/Vitaliy-1/oldGregg/commit/34f1a1ee6c6f1b5c28e8e3deb92608ba999b166d

Closed.
